version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - 2181:2181
    extra_hosts:
      - moby:127.0.0.1
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test-topic"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    extra_hosts:
      - moby:127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reactive-source:
    image: reactive-source:0.0.1-SNAPSHOT
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:9092
      FUNCTION_GENERATOR_INTERVAL: 1